CXXFLAGS=-I. -I../libcpputils -I../libgixpp -std=c++17
LDFLAGS=

STATIC_LIBS=../libcpputils/libcpputils.a ../libgixpp/libgixpp.a

DEPS = main.cpp
OBJS = main.o

.PHONY: all clean

all: gixpp

gixpp: $(OBJS) $(STATIC_LIBS)
	$(CXX) -o $@ $(OBJS) $(STATIC_LIBS)

%.o: %.cpp $(DEPS)
	$(CXX) -c -o  $@ $< $(CXXFLAGS)

clean:
	rm -f gixpp *.o
