/*
This file is part of Gix-IDE, an IDE and platform for GnuCOBOL
Copyright (C) 2021 Marco Ridoni

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
USA.
*/

#pragma once

// CHANGE: added <fstream> for new std::ifstream member "instream":
#include <fstream>
#include <string>
#include <map>

// Generated by bison:
#include "gix_esql_parser.hh"

// CHANGE: replaced `#define YY_DECL ...` here with #include of new
// lexer class:
#include "GixEsqlLexer.hh"

#include "ESQLDefinitions.h"
#include "GixPreProcessor.h"

// Conducting the whole scanning and parsing of Calc++.
class gix_esql_driver
{
public:
    gix_esql_driver ();
    virtual ~gix_esql_driver ();

#pragma region Options

    // We only have here the flags connected to parsing, other flags
    // are handled in the code generation module
    bool opt_preprocess_copy_files;
    bool opt_use_anonymous_params;

#pragma endregion

#pragma region Parse/Scanner stuff
    int result;
    
    // CHANGE: add lexer object as a member
    GixEsqlLexer lexer;

    // CHANGE: add ifstream object as a member
    std::ifstream instream;

    // Handling the scanner.
    void scan_begin ();
    void scan_end ();
    bool trace_scanning;
    
    // Run the parser on file F.
    // Return 0 on success.
    int parse (GixPreProcessor *gpp, const QString& f);
    // The name of the file being parsed.
    // Used later to pass the file name to the location tracker.
    std::string file;
    // Whether parser traces should be generated.
    bool trace_parsing;

    // Error handling.
    void error (const yy::location& l, const std::string& m);
    void error (const std::string& m);

#pragma endregion


#pragma region ESQL data structures

    //QList<cb_sql_token_t> *cb_sql_list_dup(const QList<cb_sql_token_t> *orig);
    
    //struct cb_sql_list *cb_text_list_add(struct cb_sql_list *list, QString text);
    QList<cb_sql_token_t> *cb_text_list_add(QList<cb_sql_token_t> *list, QString text);

    //struct cb_sql_list *cb_concat_text_list(struct cb_sql_list *list, struct cb_sql_list *targetlist);
    QList<cb_sql_token_t> *cb_concat_text_list(QList<cb_sql_token_t> *list, QList<cb_sql_token_t> *targetlist);

    QString cb_host_list_add(QList<cb_hostreference_ptr> *list, QString text);
    QString cb_host_list_add_force(QList<cb_hostreference_ptr> *list, QString text);
    
    void cb_res_host_list_add(QList<cb_res_hostreference_ptr> *list, QString text);
    
    int cb_search_list(QString text);
    
    void cb_set_cursorname(QString text);
    void cb_set_commandname(QString text);
    void cb_set_cursor_hold(bool h);

    int build_picture(const QString str, cb_field_ptr pic);
    cb_field_ptr cb_build_field_tree(int level, QString, cb_field_ptr last_field);

    void put_startup_exec_list();
    void put_exec_list();

    int startlineno;
    int endlineno;
    int hostlineno;
    int period;
    int sqlnum;
    int command_putother;
    QString filenameID;
    int currenthostno;
    int cursor_hold;
    QString commandname;
    QString cursorname;
    QString sqlname;
    QString incfilename;

    int orig_state = 0;

    int hostreferenceCount;
    QList<cb_hostreference_ptr> *host_reference_list;
    QList<cb_res_hostreference_ptr> *res_host_reference_list;
    QList<cb_sql_token_t> *sql_list;
    QList<cb_exec_sql_stmt_ptr> *exec_list;

    cb_field_ptr current_field;
    cb_field_ptr description_field;

    bool has_esql_in_cbl_copybooks;
    bool procedure_division_started = false;

    bool in_ws_section = false;
    bool in_linkage_section = false;
    bool in_file_section = false;

#pragma endregion

#pragma region Management
    GixPreProcessor *pp_inst;
    
    QMap<QString, cb_field_ptr> field_map;

    QMap<QString, srcLocation> paragraphs;

    QString program_id;

#pragma endregion

};
