/*
This file is part of Gix-IDE, an IDE and platform for GnuCOBOL
Copyright (C) 2021 Marco Ridoni

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
USA.
*/

#include "CobolUtils.h"
#include "SysUtils.h"

static QSet<QString> reserved_words;

bool CobolUtils::isReservedWord(QString s)
{
	if (reserved_words.size() == 0) {
		init_reserved_words_set();
	}

	return reserved_words.contains(s.toUpper());
}

void CobolUtils::resetReservedWordsSet()
{
	reserved_words.clear();
	init_reserved_words_set();
}

QString CobolUtils::extractProgramId(const QString &filename)
{
	if (filename.isEmpty() || !QFile::exists(filename))
		return QString();

	QList<QString> lines = SysUtils::FileReadLines(filename, 250);
	for (QString ln : lines) {
		if (ln.contains("PROGRAM-ID", Qt::CaseSensitivity::CaseInsensitive)) {
			QString pid = ln.replace("PROGRAM-ID", "", Qt::CaseSensitivity::CaseInsensitive);
			pid = pid.replace(".", "").trimmed();
			return pid;
		}
	}

	return QString();
}



void CobolUtils::init_reserved_words_set()
{
	reserved_words << 
		"ACCEPT" <<
		"ACCESS" <<
		"ACQUIRE" <<
		"ACTIVE-CLASS" <<
		"ACTUAL" <<
		"ADD" <<
		"ADDRESS" <<
		"ADVANCING" <<
		"AFP-5A" <<
		"AFTER" <<
		"ALL" <<
		"ALLOCATE" <<
		"ALLOW" <<
		"ALPHABET" <<
		"ALPHABETIC" <<
		"ALPHABETIC-LOWER" <<
		"ALPHABETIC-UPPER" <<
		"ALPHANUMERIC" <<
		"ALPHANUMERIC-EDITED" <<
		"ALSO" <<
		"ALTER" <<
		"ALTERNATE" <<
		"AND" <<
		"ANY" <<
		"APPLY" <<
		"ARE" <<
		"AREA" <<
		"AREAS" <<
		"AS" <<
		"ASCENDING" <<
		"ASSIGN" <<
		"AT" <<
		"AUTHOR" <<
		"AUTO_HYPHEN-SKIP" <<
		"AUTO-SKIP" <<
		"AUTOMATIC" <<
		"AND" <<
		"EXOR" <<
		"LEFT" <<
		"NOT" <<
		"OR" <<
		"RIGHT" <<
		"XOR" <<
		"BACKWARD" <<
		"BASED" <<
		"BASIS" <<
		"BEEP" <<
		"BEFORE" <<
		"BEGINNING" <<
		"BINARY" <<
		"BINARY-CHAR" <<
		"BINARY-DOUBLE" <<
		"BINARY-LONG" <<
		"BINARY-SHORT" <<
		"BIT" <<
		"BLANK" <<
		"BLOCK" <<
		"BOOLEAN" <<
		"BOTTOM" <<
		"BROWSING" <<
		"BY" <<
		"C01" <<
		"C02" <<
		"C03" <<
		"C04" <<
		"C05" <<
		"C06" <<
		"C07" <<
		"C08" <<
		"C09" <<
		"C10" <<
		"C11" <<
		"C12" <<
		"CALL" <<
		"CALL-CONVENTION" <<
		"CALLED" <<
		"CANCEL" <<
		"CBL" <<
		"CBL-CTR" <<
		"CD" <<
		"CF" <<
		"CH" <<
		"CHAIN" <<
		"CHAINING" <<
		"CHANGED" <<
		"CHARACTER" <<
		"CHARACTERS" <<
		"CHECKING" <<
		"CLASS" <<
		"CLASS-CONTROL" <<
		"CLASS-ID" <<
		"CLASS-OBJECT" <<
		"CLOCK-UNITS" <<
		"CLOSE" <<
		"COBOL" <<
		"CODE" <<
		"CODE-SET" <<
		"COERCION" <<
		"COL" <<
		"COLLATING" <<
		"COLS" <<
		"COLUMN" <<
		"COLUMNS" <<
		"COM-REG" <<
		"COMMA" <<
		"COMMIT" <<
		"COMMITMENT" <<
		"COMMON" <<
		"COMMUNICATION" <<
		"COMP" <<
		"COMP-0" <<
		"COMP-1" <<
		"COMP-2" <<
		"COMP-3" <<
		"COMP-4" <<
		"COMP-5" <<
		"COMP-6" <<
		"COMP-X" <<
		"COMPUTATIONAL" <<
		"COMPUTATIONAL-0" <<
		"COMPUTATIONAL-1" <<
		"COMPUTATIONAL-2" <<
		"COMPUTATIONAL-3" <<
		"COMPUTATIONAL-4" <<
		"COMPUTATIONAL-5" <<
		"COMPUTATIONAL-6" <<
		"COMPUTATIONAL-X" <<
		"COMPUTE" <<
		"CONFIGURATION" <<
		"CONSOLE" <<
		"CONSTANT" <<
		"CONTAINS" <<
		"CONTENT" <<
		"CONTINUE" <<
		"CONTROL" <<
		"CONTROL-AREA" <<
		"CONTROLS" <<
		"CONVERT" <<
		"CONVERTING" <<
		"COPY" <<
		"CORE-INDEX" <<
		"CORR" <<
		"CORRESPONDING" <<
		"COUNT" <<
		"CREATING" <<
		"CRT" <<
		"CRT-UNDER" <<
		"CSP" <<
		"CURRENCY" <<
		"CURRENT-DATE" <<
		"CURSOR" <<
		"CYL-INDEX" <<
		"CYL-OVERFLOW" <<
		"DATA" <<
		"DATABASE-KEY" <<
		"DATABASE_KEY-LONG" <<
		"DATE" <<
		"DATE-COMPILED" <<
		"DATE-WRITTEN" <<
		"DAY" <<
		"DAY_OF-WEEK" <<
		"DBCS" <<
		"DE" <<
		"DEBUG" <<
		"DEBUG-CONTENTS" <<
		"DEBUG-ITEM" <<
		"DEBUG-LINE" <<
		"DEBUG-NAME" <<
		"DEBUG_SU1" <<
		"DEBUG_SU2" <<
		"DEBUG_SU3" <<
		"DEBUGGING" <<
		"DECIMAL-POINT" <<
		"DECLARATIVES" <<
		"DEFAULT" <<
		"DEFINITION" <<
		"DELETE" <<
		"DELIMITED" <<
		"DELIMITER" <<
		"DEPENDING" <<
		"DESCENDING" <<
		"DESTINATION" <<
		"DETAIL" <<
		"DISABLE" <<
		"DISC" <<
		"DISK" <<
		"DISP" <<
		"DISPLAY" <<
		"DISPLAY-1" <<
		"DISPLAY-ST" <<
		"DIVIDE" <<
		"DIVISION" <<
		"DOWN" <<
		"DROP" <<
		"DUPLICATES" <<
		"DYNAMIC" <<
		"EBCDIC" <<
		"ECHO" <<
		"EGCS" <<
		"EGI" <<
		"EJECT" <<
		"ELSE" <<
		"EMI" <<
		"EMPTY-CHECK" <<
		"ENABLE" <<
		"END" <<
		"END-ACCEPT" <<
		"END-ADD" <<
		"END-CALL" <<
		"END-CHAIN" <<
		"END-COMPUTE" <<
		"END-DELETE" <<
		"END-DISPLAY" <<
		"END-DIVIDE" <<
		"END-EVALUATE" <<
		"END-IF" <<
		"END-INVOKE" <<
		"END-MULTIPLY" <<
		"END_OF-PAGE" <<
		"END-PERFORM" <<
		"END-READ" <<
		"END-RECEIVE" <<
		"END-RETURN" <<
		"END-REWRITE" <<
		"END-SEARCH" <<
		"END-START" <<
		"END-STRING" <<
		"END-SUBTRACT" <<
		"END-UNSTRING" <<
		"END-WAIT" <<
		"END-WRITE" <<
		"ENDING" <<
		"ENTER" <<
		"ENTRY" <<
		"ENVIRONMENT" <<
		"EOP" <<
		"EQUAL" <<
		"EQUALS" <<
		"ERROR" <<
		"ESCAPE" <<
		"ESI" <<
		"EVALUATE" <<
		"EVENT-POINTER" <<
		"EVERY" <<
		"EXAMINE" <<
		"EXCEEDS" <<
		"EXCEPTION" <<
		"EXCEPTION-OBJECT" <<
		"EXCESS-3" <<
		"EXCLUSIVE" <<
		"EXEC" <<
		"EXECUTE" <<
		"EXHIBIT" <<
		"EXIT" <<
		"EXTEND" <<
		"EXTENDED" <<
		"EXTENDED-SEARCH" <<
		"EXTERNAL" <<
		"EXTERNALLY-DESCRIBED-KEY" <<
		"FACTORY" <<
		"FALSE" <<
		"FD" <<
		"FH--FCD" <<
		"FH--KEYDEF" <<
		"FILE" <<
		"FILE-CONTROL" <<
		"FILE-ID" <<
		"FILE-LIMIT" <<
		"FILE-LIMITS" <<
		"FILLER" <<
		"FINAL" <<
		"FIRST" <<
		"FIXED" <<
		"FLOAT-EXTENDED" <<
		"FLOAT-LONG" <<
		"FLOAT-SHORT" <<
		"FOOTING" <<
		"FOR" <<
		"FREE" <<
		"FROM" <<
		"FUNCTION" <<
		"FUNCTION-ID" <<
		"GENERATE" <<
		"GIVING" <<
		"GLOBAL" <<
		"GO" <<
		"GOBACK" <<
		"GREATER" <<
		"GRID" <<
		"GROUP" <<
		"HEADING" <<
		"HIGH-VALUE" <<
		"HIGH-VALUES" <<
		"I-O" <<
		"I_O-CONTROL" <<
		"ID" <<
		"IDENTIFICATION" <<
		"IDENTIFIED" <<
		"IF" <<
		"IGNORE" <<
		"IN" <<
		"INDEX" <<
		"INDEXED" <<
		"INDIC" <<
		"INDICATE" <<
		"INDICATOR" <<
		"INDICATORS" <<
		"INHERITING" <<
		"INHERITS" <<
		"INITIAL" <<
		"INITIALIZE" <<
		"INITIATE" <<
		"INPUT" <<
		"INPUT-OUTPUT" <<
		"INSERT" <<
		"INSPECT" <<
		"INSTALLATION" <<
		"INTEGER" <<
		"INTERFACE" <<
		"INTERFACE-ID" <<
		"INTO" <<
		"INVALID" <<
		"INVOKE" <<
		"INVOKED" <<
		"IS" <<
		"JAPANESE" <<
		"JUST" <<
		"JUSTIFIED" <<
		"KANJI" <<
		"KEPT" <<
		"KEY" <<
		"KEYBOARD" <<
		"LABEL" <<
		"LAST" <<
		"LEADING" <<
		"LEAVE" <<
		"LEFT" <<
		"LEFT-JUSTIFY" <<
		"LEFTLINE" <<
		"LENGTH" <<
		"LENGTH-CHECK" <<
		"LESS" <<
		"LIMIT" <<
		"LIMITS" <<
		"LIN" <<
		"LINAGE" <<
		"LINAGE-COUNTER" <<
		"LINE" <<
		"LINE-COUNTER" <<
		"LINES" <<
		"LINKAGE" <<
		"LOCAL-STORAGE" <<
		"LOCK" <<
		"LOCKING" <<
		"LOW-VALUE" <<
		"LOW-VALUES" <<
		"LOWER" <<
		"MASTER-INDEX" <<
		"MEMORY" <<
		"MERGE" <<
		"MESSAGE" <<
		"METACLASS" <<
		"METHOD" <<
		"METHOD-ID" <<
		"MODE" <<
		"MODIFIED" <<
		"MODULES" <<
		"MONITOR-POINTER" <<
		"MORE-LABELS" <<
		"MOVE" <<
		"MULTIPLE" <<
		"MULTIPLY" <<
		"MUTEX-POINTER" <<
		"NAME" <<
		"NAMED" <<
		"NATIONAL" <<
		"NATIONAL-EDITED" <<
		"NATIVE" <<
		"NCHAR" <<
		"NEGATIVE" <<
		"NESTED" <<
		"NEXT" <<
		"NO" <<
		"NO-ECHO" <<
		"NOMINAL" <<
		"NOT" <<
		"NOTE" <<
		"NSTD-REELS" <<
		"NULL" <<
		"NULLS" <<
		"NUMBER" <<
		"NUMBERS" <<
		"NUMERIC" <<
		"NUMERIC-EDITED" <<
		"O-FILL" <<
		"OBJECT" <<
		"OBJECT-COMPUTER" <<
		"OBJECT-ID" <<
		"OBJECT-STORAGE" <<
		"OCCURS" <<
		"OF" <<
		"OFF" <<
		"OMITTED" <<
		"ON" <<
		"OOSTACKPTR" <<
		"OPEN" <<
		"OPTIONAL" <<
		"OPTIONS" <<
		"OR" <<
		"ORDER" <<
		"ORGANIZATION" <<
		"OTHER" <<
		"OTHERWISE" <<
		"OUTPUT" <<
		"OVERFLOW" <<
		"OVERLINE" <<
		"OVERRIDE" <<
		"PACKED-DECIMAL" <<
		"PADDING" <<
		"PAGE" <<
		"PAGE-COUNTER" <<
		"PASSWORD" <<
		"PERFORM" <<
		"PF" <<
		"PH" <<
		"PIC" <<
		"PICTURE" <<
		"PLUS" <<
		"POINTER" <<
		"POS" <<
		"POSITION" <<
		"POSITIONING" <<
		"POSITIVE" <<
		"PRESENT" <<
		"PRINT" <<
		"PRINT-SWITCH" <<
		"PRINTER" <<
		"PRINTER-1" <<
		"PRINTING" <<
		"PRIOR" <<
		"PRIVATE" <<
		"PROCEDURE" <<
		"PROCEDURE-POINTER" <<
		"PROCEDURES" <<
		"PROCEED" <<
		"PROCESS" <<
		"PROCESSING" <<
		"PROGRAM" <<
		"PROGRAM-ID" <<
		"PROGRAM-POINTER" <<
		"PROMPT" <<
		"PROPERTY" <<
		"PROTECTED" <<
		"PUBLIC" <<
		"PURGE" <<
		"QUEUE" <<
		"QUOTE" <<
		"QUOTES" <<
		"RAISE" <<
		"RAISING" <<
		"RANDOM" <<
		"RANGE" <<
		"RD" <<
		"READ" <<
		"READING" <<
		"READY" <<
		"RECEIVE" <<
		"RECORD" <<
		"RECORD-OVERFLOW" <<
		"RECORDING" <<
		"RECORDS" <<
		"RECURSIVE" <<
		"REDEFINES" <<
		"REDEFINITION" <<
		"REEL" <<
		"REFERENCE" <<
		"REFERENCES" <<
		"RELATIVE" <<
		"RELEASE" <<
		"RELOAD" <<
		"REMAINDER" <<
		"REMARKS" <<
		"REMOVAL" <<
		"RENAMES" <<
		"REORG-CRITERIA" <<
		"REPEATED" <<
		"REPLACE" <<
		"REPLACING" <<
		"REPORT" <<
		"REPORTING" <<
		"REPORTS" <<
		"REPOSITORY" <<
		"REREAD" <<
		"RERUN" <<
		"RESERVE" <<
		"RESERVED" <<
		"RESET" <<
		"RESTRICTED" <<
		"RESUME" <<
		"RETRY" <<
		"RETURN" <<
		"RETURN-CODE" <<
		"RETURNING" <<
		"REVERSED" <<
		"REWIND" <<
		"REWRITE" <<
		"RF" <<
		"RH" <<
		"RIGHT" <<
		"RIGHT-JUSTIFY" <<
		"ROLLBACK" <<
		"ROLLING" <<
		"ROUNDED" <<
		"RUN" <<
		"S01" <<
		"S02" <<
		"S03" <<
		"S04" <<
		"S05" <<
		"SAME" <<
		"SCREEN" <<
		"SD" <<
		"SEARCH" <<
		"SECTION" <<
		"SECURITY" <<
		"SEEK" <<
		"SEGMENT" <<
		"SEGMENT-LIMIT" <<
		"SELECT" <<
		"SELECTIVE" <<
		"SELF" <<
		"SELFCLASS" <<
		"SEMAPHORE-POINTER" <<
		"SEND" <<
		"SENTENCE" <<
		"SEPARATE" <<
		"SEQUENCE" <<
		"SEQUENTIAL" <<
		"SERVICE" <<
		"SET" <<
		"SHARING" <<
		"SHIFT-IN" <<
		"SHIFT-OUT" <<
		"SIGN" <<
		"SIZE" <<
		"SKIP1" <<
		"SKIP2" <<
		"SKIP3" <<
		"SORT" <<
		"SORT-CONTROL" <<
		"SORT_CORE-SIZE" <<
		"SORT_FILE-SIZE" <<
		"SORT-MERGE" <<
		"SORT-MESSAGE" <<
		"SORT_MODE-SIZE" <<
		"SORT-OPTION" <<
		"SORT-RETURN" <<
		"SORT-TAPE" <<
		"SORT-TAPES" <<
		"SOURCE" <<
		"SOURCE-COMPUTER" <<
		"SOURCES" <<
		"SPACE" <<
		"SPACE-FILL" <<
		"SPACES" <<
		"SPECIAL-NAMES" <<
		"STANDARD" <<
		"STANDARD-1" <<
		"STANDARD-2" <<
		"STANDARD-3" <<
		"START" <<
		"STARTING" <<
		"STATUS" <<
		"STOP" <<
		"STRING" <<
		"SUB_QUEUE-1" <<
		"SUB_QUEUE-2" <<
		"SUB_QUEUE-3" <<
		"SUBFILE" <<
		"SUBTRACT" <<
		"SUM" <<
		"SUPER" <<
		"SUPPRESS" <<
		"SYMBOLIC" <<
		"SYNC" <<
		"SYNCHRONIZED" <<
		"SYSIN" <<
		"SYSIPT" <<
		"SYSLST" <<
		"SYSOUT" <<
		"SYSPCH" <<
		"SYSPUNCH" <<
		"SYSTEM-DEFAULT" <<
		"TAB" <<
		"TABLE" <<
		"TALLY" <<
		"TALLYING" <<
		"TAPE" <<
		"TAPES" <<
		"TERMINAL" <<
		"TERMINATE" <<
		"TEST" <<
		"TEXT" <<
		"THAN" <<
		"THEN" <<
		"THREAD-LOCAL" <<
		"THREAD_LOCAL-STORAGE" <<
		"THREAD-POINTER" <<
		"THROUGH" <<
		"THRU" <<
		"TIME" <<
		"TIME_OF-DAY" <<
		"TIME-OUT" <<
		"TIMEOUT" <<
		"TIMES" <<
		"TITLE" <<
		"TO" <<
		"TOP" <<
		"TOTALED" <<
		"TOTALING" <<
		"TRACE" <<
		"TRACK-AREA" <<
		"TRACK-LIMIT" <<
		"TRACKS" <<
		"TRAILING" <<
		"TRAILING-SIGN" <<
		"TRANSACTION" <<
		"TRANSFORM" <<
		"TRUE" <<
		"TRY" <<
		"TYPE" <<
		"TYPEDEF" <<
		"UNEQUAL" <<
		"UNIT" <<
		"UNITS" <<
		"UNIVERSAL" <<
		"UNLOCK" <<
		"UNSTRING" <<
		"UNTIL" <<
		"UP" <<
		"UPDATE" <<
		"UPON" <<
		"UPPER" <<
		"UPSI-0" <<
		"UPSI-1" <<
		"UPSI-2" <<
		"UPSI-3" <<
		"UPSI-4" <<
		"UPSI-5" <<
		"UPSI-6" <<
		"UPSI-7" <<
		"USAGE" <<
		"USE" <<
		"USER" <<
		"USER-DEFAULT" <<
		"USING" <<
		"VALID" <<
		"VALIDATE" <<
		"VALUE" <<
		"VALUES" <<
		"VARIABLE" <<
		"VARYING" <<
		"WAIT" <<
		"WHEN" <<
		"WHEN-COMPILED" <<
		"WITH" <<
		"WORDS" <<
		"WORKING-STORAGE" <<
		"WRITE" <<
		"WRITE-ONLY" <<
		"WRITE-VERIFY" <<
		"WRITING" <<
		"ZERO" <<
		"ZERO-FILL" <<
		"ZEROES" <<
		"ZEROS";
}
