CXXFLAGS=-fPIC -I ../libgixsql -std=c++17
DEPS = DbInterfaceODBC.h
OBJS = DbInterfaceODBC.o  dblib.o

LDFLAGS=-lm -lodbc

all: libgixsql-odbc.so

%.o: %.cpp $(DEPS)
	$(CXX) -c -o  $@ $< $(CXXFLAGS)

libgixsql-odbc.so: $(OBJS)
	$(CXX) -shared -o $@ -Wl,--out-implib,libgixsql-odbc.a $^ $(CXXFLAGS) $(LDFLAGS)

.PHONY: clean

clean:
	rm -f libgixsql-odbc.so *.o
