name: gix-ide-debian-packages

on:
  workflow_dispatch
  
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  GIXIDEMAJ: 1
  GIXIDEMIN: 1
  GIXIDEREL: 1
  GIX_REVISION: ${{ github.run_number }}  
  GIXSQLMAJ: 1
  GIXSQLMIN: 0
  GIXSQLREL: 19  
  GIX_SQL_VERSION: 1.0.19
  BUILD_CONFIGURATION: release
  HOST_PLATFORM: x64  

permissions:
  contents: read

jobs:
  debian-10-x64:
    runs-on: ubuntu-latest
    container:
      image: debian:10
#      env:
#        NODE_ENV: development
#      ports:
#        - 80
#      volumes:
#        - my_docker_volume:/volume_mount
#      options: --cpus 1
      
    steps:
    
    - name: Build
      run: |
        export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        apt update
        apt install -y build-essential qt5-default qtbase5-dev libqt5xmlpatterns5-dev libqtermwidget5-0-dev libdwarf-dev libelfin-dev qttools5-dev qttools5-dev-tools libmariadb-dev-compat libmariadb-dev libpq-dev unixodbc-dev flex libnanomsg-dev libspdlog-dev libfmt-dev git wget cmake patchelf imagemagick
        git clone --recurse-submodules https://github.com/mridoni/gix.git .
        echo "HOST_PLATFORM      : ${{env.HOST_PLATFORM}}"
        echo "BUILD_CONFIGURATION: ${{env.BUILD_CONFIGURATION}}"
        wget http://ftp.debian.org/debian/pool/main/b/bison/bison_3.7.5+dfsg-1_amd64.deb
        dpkg -i bison_3.7.5+dfsg-1_amd64.deb
        : # cd gix-ide
        chmod 755 ./prepbuild.sh && ./prepbuild.sh /E
        cd ./libs/nng
        cmake -DBUILD_SHARED_LIBS=OFF
        make
        cd ../..      
        qmake CONFIG+=${{ env.BUILD_CONFIGURATION }} USE_BUNDLED_NNG=1
        make -j 2

    
    - name: Build package
      shell: bash
      env:
        DIST: debian-10
      run: |
        export WORKSPACE=$(pwd)
        echo "WORKSPACE: $WORKSPACE"
        chmod 755 $WORKSPACE/deploy/installers/linux/mkdeb.sh && $WORKSPACE/deploy/installers/linux/mkdeb.sh
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      env:
        DIST: debian-10      
      with:
        name: gix-ide-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXIDEMAJ}}.${{ env.GIXIDEMIN}}.${{ env.GIXIDEREL}}-${{ env.GIX_REVISION}}
        path: |
          ./gix-ide-${{ env.DIST }}-${{ env.HOST_PLATFORM }}-${{ env.GIXIDEMAJ}}.${{ env.GIXIDEMIN}}.${{ env.GIXIDEREL}}-${{ env.GIX_REVISION}}.deb

